services:
  mcas-scraper:
    build: .
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
      - ./debug:/app/debug
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json
